"""CLI: `python -m acv.modeling.cli train` and `evaluate`.

Pipeline:
    train:
        - Load features_v1.parquet and split into train/test.
        - Run CV (StratifiedGroupKFold) on EVERY pipeline in
          `PIPELINES`, capture OOF metrics.
        - Persist `reports/model_card.md`, `reports/model_selection.csv`
          and the OOF prediction parquet.
    evaluate (champion):
        - Refit champion on ALL train data.
        - Evaluate on test set with the threshold tuned in CV.
        - Bootstrap CI at patient level (1000 resamples).
        - Persist `models/champion.pkl`, extends model_card.md.

The "champion" is selected by max OOF sensitivity (with specificity
>= min) and tie-broken by AUROC. The decision is logged in agent.md.
"""
from __future__ import annotations

import argparse
import json
import pickle
import time
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
from rich.console import Console
from rich.table import Table

from acv.config import settings
from acv.modeling.aggregate import AGGREGATORS, aggregate_to_patient
from acv.modeling.cv import CVResult, run_cv
from acv.modeling.data import make_split
from acv.modeling.metrics import (
    bootstrap_metric,
    compute_metrics,
    pick_threshold_max_sensitivity_at_specificity,
    sensitivity,
)
from acv.modeling.pipelines import PIPELINES
from acv.modeling.slice_cv import SliceCVResult, _slice_oof, run_slice_cv
from acv.modeling.slice_data import make_slice_split

console = Console()

REPORTS_DIR = settings.project_root / "reports"
MODELS_DIR = settings.project_root / "models"
PROC_DIR = settings.project_root / "data" / "processed"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _pretty_table(results: list[CVResult]) -> Table:
    t = Table(title="CV Results (OOF on train)")
    t.add_column("Model")
    t.add_column("Thr", justify="right")
    t.add_column("Sens", justify="right")
    t.add_column("Sens 95% CI", justify="right")
    t.add_column("Spec", justify="right")
    t.add_column("AUROC", justify="right")
    t.add_column("AUROC 95% CI", justify="right")
    t.add_column("AUPRC", justify="right")
    t.add_column("Brier", justify="right")
    for r in results:
        m = r.metrics
        t.add_row(
            r.name,
            f"{r.threshold:.3f}",
            f"{m.sensitivity:.3f}",
            f"[{r.sens_ci[1]:.2f}, {r.sens_ci[2]:.2f}]",
            f"{m.specificity:.3f}",
            f"{m.auroc:.3f}",
            f"[{r.auroc_ci[1]:.2f}, {r.auroc_ci[2]:.2f}]",
            f"{m.auprc:.3f}",
            f"{m.brier:.3f}",
        )
    return t


def _save_oof(results: list[CVResult], path: Path) -> None:
    frames = []
    for r in results:
        df = pd.DataFrame(
            {
                "model": r.name,
                "patient_sk": r.oof_groups,
                "y_true": r.oof_true,
                "y_prob": r.oof_proba,
            }
        )
        frames.append(df)
    pd.concat(frames, ignore_index=True).to_parquet(path, index=False)


def _save_selection_csv(results: list[CVResult], path: Path) -> None:
    rows = []
    for r in results:
        row = {"model": r.name, **r.metrics.as_row(),
               "sens_ci_lo": r.sens_ci[1], "sens_ci_hi": r.sens_ci[2],
               "auroc_ci_lo": r.auroc_ci[1], "auroc_ci_hi": r.auroc_ci[2]}
        rows.append(row)
    pd.DataFrame(rows).sort_values("sensitivity", ascending=False).to_csv(path, index=False)


def _pick_champion(results: list[CVResult]) -> CVResult:
    eligible = [r for r in results if r.metrics.specificity >= settings.min_specificity]
    pool = eligible or results
    # max sensitivity; tie-break by AUROC
    return max(pool, key=lambda r: (r.metrics.sensitivity, r.metrics.auroc))


def _write_model_card(
    results: list[CVResult],
    champion: CVResult,
    test_metrics: dict | None,
    path: Path,
) -> None:
    lines = [
        "# Model Card — ACV Therapeutic Window Classifier (v1)",
        "",
        f"_Generated by `python -m acv.modeling.cli` at {datetime.now():%Y-%m-%d %H:%M}._",
        "",
        "## Intended use",
        "- **Apoyo clínico** al neurólogo en pacientes con ACV isquémico de tiempo de inicio desconocido.",
        "- Estima P(tiempo de evolución > 4.5 h) a partir de radiómica de TC craneal simple + clínicas básicas.",
        "- **NO** es un dispositivo médico autónomo. La decisión final es del médico tratante.",
        "",
        "## Data",
        "- Cohorte: 74 pacientes (55 train, 19 test) atendidos en Fundación Valle del Lilí.",
        "- Grano de modelado: paciente. Validación cruzada: StratifiedGroupKFold (5 folds) agrupada por `patient_sk`.",
        "- Features: 389 columnas tras pruning |Spearman|>0.95 (Phase 5), de las cuales el pipeline selecciona top-k por MI dentro de cada fold (anti-leakage).",
        "",
        f"## Decision rule (v1)",
        f"- Métrica primaria: **sensibilidad de clase 1 (>4.5 h)** sujeto a **especificidad ≥ {settings.min_specificity:.2f}**.",
        f"- Threshold tuneado en out-of-fold; champion refitted en todo train.",
        "",
        "## Cross-validation results (OOF on train)",
        "",
        "| Model | Thr | Sens | Sens 95% CI | Spec | AUROC | AUROC 95% CI | AUPRC | Brier |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in results:
        m = r.metrics
        lines.append(
            f"| `{r.name}` | {r.threshold:.3f} | {m.sensitivity:.3f} | "
            f"[{r.sens_ci[1]:.2f}, {r.sens_ci[2]:.2f}] | {m.specificity:.3f} | "
            f"{m.auroc:.3f} | [{r.auroc_ci[1]:.2f}, {r.auroc_ci[2]:.2f}] | "
            f"{m.auprc:.3f} | {m.brier:.3f} |"
        )
    lines.append("")
    lines.append(f"## Champion: `{champion.name}`")
    lines.append(
        f"- Sensibilidad OOF: **{champion.metrics.sensitivity:.3f}**  "
        f"(95% CI [{champion.sens_ci[1]:.2f}, {champion.sens_ci[2]:.2f}])"
    )
    lines.append(
        f"- Especificidad OOF: **{champion.metrics.specificity:.3f}**"
    )
    lines.append(
        f"- AUROC OOF: **{champion.metrics.auroc:.3f}**  "
        f"(95% CI [{champion.auroc_ci[1]:.2f}, {champion.auroc_ci[2]:.2f}])"
    )
    lines.append(f"- Threshold: **{champion.threshold:.3f}**")
    lines.append("")

    if test_metrics:
        lines.append("## Held-out test set (19 patients, 1 single evaluation)")
        lines.append("")
        lines.append("| metric | value | 95% CI |")
        lines.append("|---|---|---|")
        for k, v in test_metrics.items():
            if isinstance(v, dict) and "point" in v:
                lines.append(f"| {k} | {v['point']:.3f} | [{v['low']:.2f}, {v['high']:.2f}] |")
            else:
                lines.append(f"| {k} | {v} | — |")
        lines.append("")

    lines += [
        "## Limitations",
        "- N pequeño (55 train, 19 test). Las estimaciones tienen incertidumbre amplia (bootstrap CI las refleja).",
        "- Single-center cohort (FVL). Validación externa pendiente.",
        "- Sin información de timing real para los pacientes >4.5 h (target derivado de `Evolution Time`).",
        "- v1 NO ingiere imágenes DICOM directamente; depende del pipeline radiomics upstream.",
        "",
        "## Operating",
        "- Repro: `python -m acv.features.cli && python -m acv.modeling.cli train && python -m acv.modeling.cli evaluate`.",
        "- Inputs from DW: `analytics.features_v1` (74 × 389).",
        "- Anti-leakage tests: `pytest src/tests/test_features_v1.py`.",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# train
# ---------------------------------------------------------------------------


def cmd_train(args: argparse.Namespace) -> None:
    t0 = time.time()
    console.print("[cyan]==> Loading features[/]")
    split = make_split()
    console.print(f"   train: {split.n_train_patients} patients | "
                  f"test: {split.n_test_patients} patients | "
                  f"features: {len(split.feature_names)}")

    results: list[CVResult] = []
    for name, factory in PIPELINES.items():
        console.print(f"[cyan]==> CV {name}[/]")
        # clinical baseline uses the clinical-only split
        if name == "baseline_clinical_logreg":
            sub = make_split(clinical_only=True)
            r = run_cv(
                name, factory,
                sub.X_train, sub.y_train, sub.groups_train,
                seed=settings.random_seed, bootstrap_n=args.bootstrap,
                k=len(sub.feature_names),
            )
        elif name == "baseline_majority":
            r = run_cv(
                name, factory,
                split.X_train, split.y_train, split.groups_train,
                seed=settings.random_seed, bootstrap_n=args.bootstrap,
                k=None,
            )
        else:
            r = run_cv(
                name, factory,
                split.X_train, split.y_train, split.groups_train,
                seed=settings.random_seed, bootstrap_n=args.bootstrap,
                k=args.k,
            )
        results.append(r)
        m = r.metrics
        console.print(
            f"   sens={m.sensitivity:.3f} [{r.sens_ci[1]:.2f},{r.sens_ci[2]:.2f}]  "
            f"spec={m.specificity:.3f}  auroc={m.auroc:.3f}  thr={r.threshold:.3f}"
        )

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    PROC_DIR.mkdir(parents=True, exist_ok=True)
    _save_selection_csv(results, REPORTS_DIR / "model_selection.csv")
    _save_oof(results, PROC_DIR / "model_oof_predictions.parquet")

    champion = _pick_champion(results)
    console.print(_pretty_table(results))
    console.print(f"[bold green]Champion: {champion.name}[/]")

    # Save champion choice as JSON for the evaluate step.
    (REPORTS_DIR / "champion.json").write_text(
        json.dumps(
            {"name": champion.name, "threshold": champion.threshold,
             "k": args.k}, indent=2
        ),
        encoding="utf-8",
    )

    _write_model_card(results, champion, test_metrics=None,
                      path=REPORTS_DIR / "model_card.md")
    console.print(f"[bold green]Done in {time.time()-t0:.1f}s[/]")


# ---------------------------------------------------------------------------
# evaluate
# ---------------------------------------------------------------------------


def cmd_evaluate(args: argparse.Namespace) -> None:
    """One-shot test-set evaluation of the champion. Writes models/champion.pkl."""
    t0 = time.time()
    champ_path = REPORTS_DIR / "champion.json"
    if not champ_path.exists():
        raise SystemExit("Run `train` first; champion.json missing.")
    champ_info = json.loads(champ_path.read_text(encoding="utf-8"))
    name = champ_info["name"]
    threshold = float(champ_info["threshold"])
    k = champ_info.get("k") or 15

    console.print(f"[cyan]==> Refitting champion `{name}` on full train[/]")
    if name == "baseline_clinical_logreg":
        split = make_split(clinical_only=True)
        factory = PIPELINES[name]
        pipe = factory(k=len(split.feature_names), seed=settings.random_seed)
    elif name == "baseline_majority":
        split = make_split()
        pipe = PIPELINES[name](seed=settings.random_seed)
    else:
        split = make_split()
        pipe = PIPELINES[name](k=k, seed=settings.random_seed)
    pipe.fit(split.X_train, split.y_train)

    if hasattr(pipe.named_steps["est"], "predict_proba"):
        proba = pipe.predict_proba(split.X_test)[:, 1]
    else:
        proba = pipe.predict(split.X_test).astype(float)

    metrics = compute_metrics(split.y_test, proba, threshold)
    sens_at_thr = lambda yt, yp: sensitivity(yt, (yp >= threshold).astype(int))
    sens_pt, sens_lo, sens_hi = bootstrap_metric(
        split.y_test, proba, sens_at_thr,
        n_resamples=args.bootstrap, groups=split.groups_test,
        random_state=settings.random_seed,
    )
    from sklearn.metrics import roc_auc_score
    try:
        auroc_pt, auroc_lo, auroc_hi = bootstrap_metric(
            split.y_test, proba, roc_auc_score,
            n_resamples=args.bootstrap, groups=split.groups_test,
            random_state=settings.random_seed,
        )
    except ValueError:
        auroc_pt, auroc_lo, auroc_hi = metrics.auroc, float("nan"), float("nan")

    console.print(f"[bold]Test set metrics ({split.n_test_patients} patients):[/]")
    console.print(f"  threshold   = {threshold:.3f}")
    console.print(f"  sensitivity = {metrics.sensitivity:.3f}  95% CI [{sens_lo:.2f}, {sens_hi:.2f}]")
    console.print(f"  specificity = {metrics.specificity:.3f}")
    console.print(f"  AUROC       = {metrics.auroc:.3f}  95% CI [{auroc_lo:.2f}, {auroc_hi:.2f}]")
    console.print(f"  AUPRC       = {metrics.auprc:.3f}")
    console.print(f"  confusion   = {metrics.confusion}")

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    with (MODELS_DIR / "champion.pkl").open("wb") as f:
        pickle.dump(
            {
                "name": name,
                "threshold": threshold,
                "pipeline": pipe,
                "feature_names": split.feature_names,
            },
            f,
        )
    console.print(f"   wrote {MODELS_DIR / 'champion.pkl'}")

    test_dict = {
        "sensitivity": {"point": metrics.sensitivity, "low": sens_lo, "high": sens_hi},
        "specificity": {"point": metrics.specificity, "low": float('nan'), "high": float('nan')},
        "auroc": {"point": metrics.auroc, "low": auroc_lo, "high": auroc_hi},
        "auprc": metrics.auprc,
        "brier": metrics.brier,
        "tp/fp/tn/fn": f"{metrics.confusion['tp']}/{metrics.confusion['fp']}/{metrics.confusion['tn']}/{metrics.confusion['fn']}",
    }
    # rewrite model card so it includes the test block.
    csv_path = REPORTS_DIR / "model_selection.csv"
    sel_df = pd.read_csv(csv_path)
    # rebuild a fake CVResult list for the table (we only need the metrics);
    # easier: rewrite from the persisted CSV.
    md_lines = (REPORTS_DIR / "model_card.md").read_text(encoding="utf-8").splitlines()
    held_out_marker = "## Held-out test set"
    if held_out_marker in (REPORTS_DIR / "model_card.md").read_text(encoding="utf-8"):
        # already contains a test block; replace it via rewrite from scratch
        pass
    # simpler: append test section at end.
    new_block = [
        "",
        f"## Held-out test set (refitted champion = `{name}`)",
        "",
        "| metric | value | 95% CI |",
        "|---|---|---|",
        f"| sensitivity | {metrics.sensitivity:.3f} | [{sens_lo:.2f}, {sens_hi:.2f}] |",
        f"| specificity | {metrics.specificity:.3f} | — |",
        f"| AUROC       | {metrics.auroc:.3f} | [{auroc_lo:.2f}, {auroc_hi:.2f}] |",
        f"| AUPRC       | {metrics.auprc:.3f} | — |",
        f"| Brier       | {metrics.brier:.3f} | — |",
        f"| TP/FP/TN/FN | {metrics.confusion['tp']}/{metrics.confusion['fp']}/{metrics.confusion['tn']}/{metrics.confusion['fn']} | — |",
    ]
    # write a clean rewrite
    md = (REPORTS_DIR / "model_card.md").read_text(encoding="utf-8")
    if held_out_marker not in md:
        md += "\n" + "\n".join(new_block) + "\n"
    else:
        # truncate previous test block and add fresh
        idx = md.find(held_out_marker)
        # find next "## " or EOF
        rest = md[idx:]
        next_section = rest.find("\n## ", 1)
        if next_section == -1:
            md = md[:idx] + "\n".join(new_block) + "\n"
        else:
            md = md[:idx] + "\n".join(new_block) + rest[next_section:]
    (REPORTS_DIR / "model_card.md").write_text(md, encoding="utf-8")
    console.print(f"[bold green]Done in {time.time()-t0:.1f}s[/]")


# ---------------------------------------------------------------------------
# slice-level training (MIL)
# ---------------------------------------------------------------------------


def _pretty_slice_table(results: list[SliceCVResult]) -> Table:
    t = Table(title="Slice-level CV (patient-aggregated metrics)")
    t.add_column("Model")
    t.add_column("Agg")
    t.add_column("Thr", justify="right")
    t.add_column("Sens", justify="right")
    t.add_column("Sens 95% CI", justify="right")
    t.add_column("Spec", justify="right")
    t.add_column("AUROC", justify="right")
    t.add_column("AUROC 95% CI", justify="right")
    t.add_column("AUPRC", justify="right")
    t.add_column("Brier", justify="right")
    for r in results:
        m = r.metrics
        t.add_row(
            r.name, r.aggregator,
            f"{r.threshold:.3f}",
            f"{m.sensitivity:.3f}",
            f"[{r.sens_ci[1]:.2f}, {r.sens_ci[2]:.2f}]",
            f"{m.specificity:.3f}",
            f"{m.auroc:.3f}",
            f"[{r.auroc_ci[1]:.2f}, {r.auroc_ci[2]:.2f}]",
            f"{m.auprc:.3f}",
            f"{m.brier:.3f}",
        )
    return t


def cmd_train_slice(args: argparse.Namespace) -> None:
    """Slice-level CV across all candidate models + aggregator strategies."""
    t0 = time.time()
    console.print("[cyan]==> Loading slice-level data[/]")
    split = make_slice_split()
    console.print(
        f"   train: {len(split.X_train)} slices / {split.n_train_patients} patients | "
        f"test: {len(split.X_test)} slices / {split.n_test_patients} patients | "
        f"features: {len(split.feature_names)}"
    )

    # Subset of pipelines worth running on slice grain: skip clinical-only
    # (which by definition is constant per patient) and baseline_majority
    # (already trivial).
    candidates = {n: f for n, f in PIPELINES.items()
                  if n not in {"baseline_majority", "baseline_clinical_logreg"}}
    aggregators = args.aggregators.split(",") if args.aggregators else list(AGGREGATORS.keys())

    results: list[SliceCVResult] = []
    for name, factory in candidates.items():
        console.print(f"[cyan]==> Slice CV {name}  (k={args.k})[/]")
        # Compute slice-level OOF ONCE per (model, k), then reuse across all
        # aggregators. This makes the aggregator sweep nearly free.
        oof = _slice_oof(
            factory, split.X_train, split.y_train, split.groups_train,
            n_splits=5, seed=settings.random_seed, k=args.k,
        )
        for agg in aggregators:
            r = run_slice_cv(
                name, factory,
                split.X_train, split.y_train,
                split.groups_train, split.slice_weights_train,
                aggregator=agg, seed=settings.random_seed,
                bootstrap_n=args.bootstrap, k=args.k,
                calibrate=args.calibrate,
                oof_slice_precomputed=oof,
            )
            results.append(r)
            m = r.metrics
            console.print(
                f"   agg={agg:14s}  sens={m.sensitivity:.3f}  spec={m.specificity:.3f}  "
                f"auroc={m.auroc:.3f}  thr={r.threshold:.3f}"
            )

    console.print(_pretty_slice_table(results))

    # Select champion: max sensitivity s.t. spec >= min; tie-break by AUROC.
    eligible = [r for r in results if r.metrics.specificity >= settings.min_specificity]
    pool = eligible or results
    champion = max(pool, key=lambda r: (r.metrics.sensitivity, r.metrics.auroc))
    console.print(
        f"[bold green]Slice champion: {champion.name}  (aggregator={champion.aggregator})[/]"
    )

    # Persist artifacts (separate file paths from the patient-level run).
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    PROC_DIR.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(
        [{"model": r.name, "aggregator": r.aggregator, **r.metrics.as_row(),
          "sens_ci_lo": r.sens_ci[1], "sens_ci_hi": r.sens_ci[2],
          "auroc_ci_lo": r.auroc_ci[1], "auroc_ci_hi": r.auroc_ci[2]}
         for r in results]
    ).sort_values("sensitivity", ascending=False).to_csv(
        REPORTS_DIR / "model_selection_slice.csv", index=False
    )
    pd.DataFrame(
        [{"model": r.name, "aggregator": r.aggregator,
          "patient_sk": pg, "y_true": yt, "y_prob": yp}
         for r in results
         for pg, yt, yp in zip(r.oof_patient_groups, r.oof_patient_true,
                                r.oof_patient_proba)]
    ).to_parquet(PROC_DIR / "model_oof_slice_patient.parquet", index=False)

    (REPORTS_DIR / "champion_slice.json").write_text(
        json.dumps({
            "name": champion.name,
            "aggregator": champion.aggregator,
            "threshold": champion.threshold,
            "k": args.k,
            "calibrate": bool(args.calibrate),
            "oof_sensitivity": champion.metrics.sensitivity,
            "oof_specificity": champion.metrics.specificity,
            "oof_auroc": champion.metrics.auroc,
        }, indent=2),
        encoding="utf-8",
    )
    console.print(f"[bold green]Done in {time.time()-t0:.1f}s[/]")


def cmd_evaluate_slice(args: argparse.Namespace) -> None:
    """Refit slice-level champion on full train, evaluate once on test."""
    t0 = time.time()
    champ_path = REPORTS_DIR / "champion_slice.json"
    if not champ_path.exists():
        raise SystemExit("Run `train-slice` first; champion_slice.json missing.")
    info = json.loads(champ_path.read_text(encoding="utf-8"))
    name, aggregator = info["name"], info["aggregator"]
    threshold = float(info["threshold"])
    k = info.get("k") or 15
    calibrate = bool(info.get("calibrate", False))

    console.print(f"[cyan]==> Refitting slice champion `{name}` (agg={aggregator}, k={k}, calibrate={calibrate})[/]")
    split = make_slice_split()

    # If calibration was used in CV, we must refit Isotonic on the
    # train OOF patient-level predictions and apply it to test.
    iso = None
    if calibrate:
        from sklearn.isotonic import IsotonicRegression
        from acv.modeling.slice_cv import _slice_oof, _patient_truth

        console.print("[cyan]==> Computing train OOF for isotonic calibration[/]")
        oof_slice_train = _slice_oof(
            PIPELINES[name], split.X_train, split.y_train,
            split.groups_train, n_splits=5,
            seed=settings.random_seed, k=k,
        )
        oof_pat_train, _ = aggregate_to_patient(
            oof_slice_train, split.groups_train,
            split.slice_weights_train, aggregator=aggregator,
        )
        pat_truth_train, _ = _patient_truth(split.y_train, split.groups_train)
        iso = IsotonicRegression(out_of_bounds="clip")
        iso.fit(oof_pat_train, pat_truth_train)

    # Now train the final pipeline on FULL train and predict on test.
    pipe = PIPELINES[name](k=k, seed=settings.random_seed)
    pipe.fit(split.X_train, split.y_train)

    if hasattr(pipe.named_steps["est"], "predict_proba"):
        slice_proba = pipe.predict_proba(split.X_test)[:, 1]
    else:
        slice_proba = pipe.predict(split.X_test).astype(float)

    pat_proba, pat_groups = aggregate_to_patient(
        slice_proba, split.groups_test, split.slice_weights_test, aggregator=aggregator
    )
    if iso is not None:
        pat_proba = iso.transform(pat_proba)
    pat_truth_df = pd.DataFrame({"g": split.groups_test, "y": split.y_test}).groupby("g", sort=True)["y"].max()
    pat_truth = pat_truth_df.to_numpy()

    metrics = compute_metrics(pat_truth, pat_proba, threshold)
    sens_at_thr = lambda yt, yp: sensitivity(yt, (yp >= threshold).astype(int))
    sens_pt, sens_lo, sens_hi = bootstrap_metric(
        pat_truth, pat_proba, sens_at_thr, n_resamples=args.bootstrap,
        groups=pat_groups, random_state=settings.random_seed,
    )
    from sklearn.metrics import roc_auc_score
    try:
        _, auroc_lo, auroc_hi = bootstrap_metric(
            pat_truth, pat_proba, roc_auc_score, n_resamples=args.bootstrap,
            groups=pat_groups, random_state=settings.random_seed,
        )
    except ValueError:
        auroc_lo, auroc_hi = float("nan"), float("nan")

    console.print(f"[bold]Slice-level test metrics (n={pat_truth.size} patients):[/]")
    console.print(f"  aggregator  = {aggregator}")
    console.print(f"  threshold   = {threshold:.3f}")
    console.print(f"  sensitivity = {metrics.sensitivity:.3f}  95% CI [{sens_lo:.2f}, {sens_hi:.2f}]")
    console.print(f"  specificity = {metrics.specificity:.3f}")
    console.print(f"  AUROC       = {metrics.auroc:.3f}  95% CI [{auroc_lo:.2f}, {auroc_hi:.2f}]")
    console.print(f"  AUPRC       = {metrics.auprc:.3f}")
    console.print(f"  confusion   = {metrics.confusion}")

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    with (MODELS_DIR / "champion_slice.pkl").open("wb") as f:
        pickle.dump(
            {
                "name": name, "aggregator": aggregator, "threshold": threshold,
                "pipeline": pipe, "feature_names": split.feature_names,
                "calibrator": iso, "k": k,
            },
            f,
        )
    console.print(f"   wrote {MODELS_DIR / 'champion_slice.pkl'}")
    console.print(f"[bold green]Done in {time.time()-t0:.1f}s[/]")


# ---------------------------------------------------------------------------
# entrypoint
# ---------------------------------------------------------------------------


def _parse() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="ACV window classifier modeling pipeline.")
    sub = p.add_subparsers(dest="cmd", required=True)

    p_train = sub.add_parser("train", help="Run CV across all pipelines.")
    p_train.add_argument("--k", type=int, default=15, help="Top-K features by MI.")
    p_train.add_argument("--bootstrap", type=int, default=1000, help="Bootstrap resamples.")

    p_eval = sub.add_parser("evaluate", help="Refit champion and evaluate on test.")
    p_eval.add_argument("--bootstrap", type=int, default=1000, help="Bootstrap resamples.")

    p_ts = sub.add_parser("train-slice", help="Slice-level CV (MIL) across pipelines + aggregators.")
    p_ts.add_argument("--k", type=int, default=20, help="Top-K features by MI inside each fold.")
    p_ts.add_argument("--bootstrap", type=int, default=500, help="Bootstrap resamples.")
    p_ts.add_argument("--aggregators", type=str, default="",
                      help="Comma-separated aggregators (default: all).")
    p_ts.add_argument("--calibrate", action="store_true",
                      help="Isotonic-calibrate patient-level OOF probabilities.")

    p_es = sub.add_parser("evaluate-slice", help="Refit slice champion + 1-shot test eval.")
    p_es.add_argument("--bootstrap", type=int, default=1000, help="Bootstrap resamples.")

    return p.parse_args()


if __name__ == "__main__":
    args = _parse()
    if args.cmd == "train":
        cmd_train(args)
    elif args.cmd == "evaluate":
        cmd_evaluate(args)
    elif args.cmd == "train-slice":
        cmd_train_slice(args)
    elif args.cmd == "evaluate-slice":
        cmd_evaluate_slice(args)
